Fix UBIFS build
sudo command fails to access stdin for password when it is called
from a shell script, which is executed during Android build.
The error was not present in the earlier versions of Android
and was introduced after switching to ninja build system.

Error log is the following:
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1

Because of this  convert_extfs_to_ubifs script call
has been moved to mksdcard script and system.ubifs.img
is being created if it does not exist or in case that
it has an older date compared to system.img.

Build procedure is simpler after this change when compared to
previous versions Android UBIFS build. It does not pause
the build and wait for password because of EXT4/UBIFS conversion.
Instead, conversion is being done right before burning
the image to sdcard and this is only done if needed.
Burning the image required root access even before
this change, so this step will not require additional
user interaction.

Change-Id: I066ee07ed4b219b2bb91467d1cf576b8a36a625b
Signed-off-by: Dragan Cecavac <dragan.cecavac@imgtec.com>

diff --git a/sdcardinstaller/mksdcard b/sdcardinstaller/mksdcard
--- a/sdcardinstaller/mksdcard
+++ b/sdcardinstaller/mksdcard
@@ -74,8 +74,15 @@ bootImg=${BOOTIMG:-${OUT}/boot.img}
 [ -e "${bootImg}" ] || die "Android boot image '${bootImg}' not found"
 recoveryImg=${RECOVERYIMG:-${OUT}/recovery.img}
 [ -e "${recoveryImg}" ] || die "Android recovery image '${recoveryImg}' not found"
-systemImg=${SYSTEMIMG:-${OUT}/system.img}
-[ -e "${systemImg}" ] || die "Android system image '${systemImg}' not found"
+systemImgEXT4=${SYSTEMIMG:-${OUT}/system.img}
+[ -e "${systemImgEXT4}" ] || die "Android system image '${systemImgEXT4}' not found"
+
+systemImg=${OUT}/system.ubifs.img
+if [[ ! -f $systemImg || "$systemImg" -ot "$systemImgEXT4" ]]; then
+  echo "Converting the image to UBIFS"
+  sh $ANDROID_BUILD_TOP/device/imgtec/ci20/sdcardinstaller/convert_extfs_to_ubifs $systemImgEXT4 $systemImg
+  echo "CI20 specific target system fs done"
+fi
 
 # Check that systemImg is a ubifs
 # FIXME: unfortunately file(1) is not very helpful...
