Introduce loadable dtb support
dtb/src/ci20-sdcard.dts and dtb/src/ci20-nand.dts empty files
have been added as a foundation for sdcard/nand specific device
tree support. These files will be combined with kernel device tree
specification when device tree blobs are created.

sdcard scripts have been updated to burn dtb and arrange U-Boot to
load dtb to 0x76000000 address.

build-dtb.sh script has been introduced. It creates dtb/ci20-sdcard.dtb and
dtb/ci20-nand.dtb prebuilt dtbs based on content of dtb/src directory and
files included from kernel sources specified by --kernel_dir= option.

Change-Id: I0cd24986d370781c9b02460af02a55b52f302aa1
Signed-off-by: Dragan Cecavac <dragan.cecavac@mips.com>

diff --git a/sdcardinstaller/mksdcard-ext4 b/sdcardinstaller/mksdcard-ext4
--- a/sdcardinstaller/mksdcard-ext4
+++ b/sdcardinstaller/mksdcard-ext4
@@ -133,6 +133,9 @@ init_image_constants()
   readonly systemImg=${SYSTEMIMG:-${OUT}/system.img}
   [ -e "${systemImg}" ] || die "Android system image '${systemImg}' not found"
 
+  readonly dtb=$ANDROID_BUILD_TOP/device/imgtec/ci20/dtb/ci20-sdcard.dtb
+  [ -e "${dtb}" ] || die "Kernel device tree blob '${dtb}' not found"
+
   readonly envSize=$((32 * 1024))
 
   readonly bs_uBootSPL=512
@@ -150,13 +153,16 @@ init_uboot_env_constants()
 {
   readonly mmcPart="mmc 0:1"
   readonly bootImgAddr=0x88000000
+  readonly dtbAddr=0x87000000
   readonly baudRate=115200
   readonly stdioCfg="eserial0,eserial4"
 
   # Command to boot Android from MMC
-  readonly androidInitCmd="ext4load ${mmcPart} ${bootImgAddr} boot.img; boota ${bootImgAddr}"
+  readonly androidInitCmd="ext4load ${mmcPart} ${bootImgAddr} boot.img; run dtbcmd; boota ${bootImgAddr}"
   # Command to set device specific MAC address
   readonly ethArgs='env set bootargs dm9000.mac_addr=${ethaddr}'
+  # Command for loading device tree blob
+  readonly dtbCmd="env set bootargs \""'${bootargs}'" dtb_addr=$dtbAddr\"; ext4load ${mmcPart} ${dtbAddr} jz4780.dtb;"
 }
 
 init_constants()
@@ -206,6 +212,7 @@ burn_uboot_env()
   echo "ainitcmd=${androidInitCmd}" > ${envText}
   echo "baudrate=${baudRate}" >> ${envText}
   echo "ethargs=${ethArgs}" >> ${envText}
+  echo "dtbcmd=${dtbCmd}" >> ${envText}
   echo "stderr=${stdioCfg}" >> ${envText}
   echo "stdin=${stdioCfg}" >> ${envText}
   echo "stdout=${stdioCfg}" >> ${envText}
@@ -232,6 +239,9 @@ burn_android_images()
 
   # copy Android recovery image
   sudo cp -v ${recoveryImg} ${sdMount}/
+
+  # copy kernel device tree blob
+  sudo cp -v ${dtb} ${sdMount}/jz4780.dtb
 
   echo
   echo "Please wait, writing system.img"
@@ -269,6 +279,7 @@ verify_burned_sd_card()
   verify_burned_segment ${bootImg} ${sdMount}/boot.img
   verify_burned_segment ${recoveryImg} ${sdMount}/recovery.img
   verify_burned_segment ${systemImg} ${device}${partSystem}
+  verify_burned_segment ${dtb} ${sdMount}/jz4780.dtb
 
   echo "Successfully verified SD card content"
 }
diff --git a/sdcardinstaller/mksdcard-ubifs b/sdcardinstaller/mksdcard-ubifs
--- a/sdcardinstaller/mksdcard-ubifs
+++ b/sdcardinstaller/mksdcard-ubifs
@@ -107,8 +107,9 @@ init_partition_layout_constants()
 
   readonly partitionLayout="${partOffset}M,${partSize}M"
 
-  readonly bootVolSize="0x1600000"             #22M
-  readonly recoveryVolSize="0x1600000"         #22M
+  readonly bootVolSize="0x1300000"             #19M
+  readonly recoveryVolSize="0x1300000"         #19M
+  readonly dtbVolSize="0x800000"               #8M
   readonly cacheVolSize="0x10000000"           #256M
   readonly userdataVolSize="0x100000000"       #4G
 
@@ -143,11 +144,17 @@ init_image_constants()
   [ -e "${systemImgEXT4}" ] || die "Android system image '${systemImgEXT4}' not found"
   readonly systemImg=${OUT}/system.ubifs.img
 
+  readonly dtb=$ANDROID_BUILD_TOP/device/imgtec/ci20/dtb/ci20-nand.dtb
+  [ -e "${dtb}" ] || die "Kernel device tree blob '${dtb}' not found"
+
   local bootImgSize=`stat -c %s ${bootImg}`
   readonly bootImgSizeHex=`echo "ibase=10; obase=16; ${bootImgSize}" | bc`
 
   local recoveryImgSize=`stat -c %s ${recoveryImg}`
   readonly recoveryImgSizeHex=`echo "ibase=10; obase=16; ${recoveryImgSize}" | bc`
+
+  local dtbSize=`stat -c %s ${dtb}`
+  readonly dtbSizeHex=`echo "ibase=10; obase=16; ${bootImgSize}" | bc`
 
   # Size of NAND U-Boot image
   local ubootImgSize=`stat -c %s ${ubootPrebuiltDir}/nand/u-boot.img`
@@ -181,13 +188,16 @@ init_uboot_env_constants()
 {
   readonly mmcPart="mmc 0:1"
   readonly bootImgAddr="0x88000000"
+  readonly dtbAddr="0x87000000"
   readonly baudRate=115200
   readonly stdioCfg="eserial0,eserial4"
 
   # Command to boot Android from NAND
-  readonly androidBootCmd="mtdparts default; ubi part boot; ubi read ${bootImgAddr} boot ${bootImgSizeHex}; boota ${bootImgAddr}"
+  readonly androidBootCmd="mtdparts default; ubi part boot; ubi read ${bootImgAddr} boot ${bootImgSizeHex}; run dtbcmd; boota ${bootImgAddr}"
   # Command to set device specific MAC address
   readonly ethArgs='env set bootargs dm9000.mac_addr=${ethaddr}'
+  # Command for loading device tree blob
+  readonly dtbCmd="env set bootargs \""'${bootargs}'" dtb_addr=$dtbAddr\"; ubi read ${dtbAddr} dtb ${dtbSizeHex}"
 
   # Commands for changing the LED color
   readonly blueLED="mw.l 0xb0010548 0x8000"
@@ -233,6 +243,7 @@ burn_nand_uboot_env()
   echo "bootcmd=run ethargs; run abootcmd" >> ${envText}
   echo "baudrate=${baudRate}" >> ${envText}
   echo "ethargs=${ethArgs}" >> ${envText}
+  echo "dtbcmd=${dtbCmd}" >> ${envText}
   echo "stderr=${stdioCfg}" >> ${envText}
   echo "stdin=${stdioCfg}" >> ${envText}
   echo "stdout=${stdioCfg}" >> ${envText}
@@ -290,6 +301,9 @@ burn_android_images()
   # copy Android recovery image
   sudo cp -v ${recoveryImg} ${sdMount}/
 
+  # copy kernel device tree blob
+  sudo cp -v ${dtb} ${sdMount}/jz4780.dtb
+
   burn_system_image
 }
 
@@ -308,10 +322,13 @@ burn_mmc_uboot_env()
   ubi part boot; \
   ubi create boot ${bootVolSize}; \
   ubi create recovery ${recoveryVolSize}; \
+  ubi create dtb ${dtbVolSize}; \
   ext4load ${mmcPart} ${lsMemAddr} boot.img; \
   ubi write ${lsMemAddr} boot ${bootImgSizeHex}; \
   ext4load ${mmcPart} ${lsMemAddr} recovery.img; \
   ubi write ${lsMemAddr} recovery ${recoveryImgSizeHex}; \
+  ext4load ${mmcPart} ${lsMemAddr} jz4780.dtb; \
+  ubi write ${lsMemAddr} dtb ${dtbSizeHex}; \
   ubi part system; \
   ubi create system ${systemVolSize}; \
   ubi create cache ${cacheVolSize}; \
@@ -372,6 +389,7 @@ verify_burned_sd_card()
   verify_burned_segment ${ubootPrebuiltDir}/nand/u-boot-spl.bin ${sdMount}/u-boot-spl.bin
   verify_burned_segment ${ubootPrebuiltDir}/nand/u-boot.img ${sdMount}/u-boot.img
   verify_burned_segment ${bootImg} ${sdMount}/boot.img
+  verify_burned_segment ${dtb} ${sdMount}/jz4780.dtb
   verify_burned_segment ${recoveryImg} ${sdMount}/recovery.img
   verify_burned_segment ${envBinNAND} ${sdMount}/u-boot-env.bin
 
